# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 10:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('location', models.CharField(max_length=100, verbose_name='location')),
                ('description', models.CharField(max_length=200)),
                ('happened_on', models.DateField(blank=True, null=True, verbose_name='happened on')),
                ('photo', models.ImageField(blank=True, upload_to='travel', verbose_name='photo')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travels', to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('place', models.CharField(max_length=100, verbose_name='place name')),
                ('subject', models.PositiveSmallIntegerField(choices=[(1, 'holiday'), (2, 'work'), (3, 'volunteering'), (4, 'just_go_away')], verbose_name='subject')),
                ('happened_on', models.DateTimeField(blank=True, null=True, verbose_name='happened on')),
                ('photo', models.ImageField(blank=True, upload_to='trip', verbose_name='photo')),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='whereami.Travel')),
            ],
        ),
    ]
