# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whereami', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('year', models.IntegerField(choices=[(1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017)], default=2017, verbose_name='year')),
                ('technique', models.IntegerField(choices=[(1, 'painting'), (2, 'linocut'), (3, 'installation'), (4, 'collage'), (5, 'photo'), (6, 'sculpture'), (7, 'else')], default=1, verbose_name='technique')),
                ('image', models.ImageField(blank=True, upload_to='art', verbose_name='image')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='description')),
                ('size', models.CharField(blank=True, max_length=100, null=True, verbose_name='size')),
                ('material', models.CharField(blank=True, max_length=100, null=True, verbose_name='used materials')),
            ],
        ),
        migrations.AlterField(
            model_name='travel',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media/travel', verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media/trip', verbose_name='photo'),
        ),
    ]
