# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 02:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whereami', '0002_artobject'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('image', models.ImageField(upload_to='travel/details', verbose_name='image')),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='whereami.Travel')),
            ],
        ),
        migrations.AlterField(
            model_name='artobject',
            name='technique',
            field=models.IntegerField(choices=[(1, 'painting'), (2, 'linocut'), (3, 'installation'), (4, 'collage'), (5, 'photo'), (6, 'sculpture'), (7, 'illustration'), (8, 'else')], default=1, verbose_name='technique'),
        ),
    ]
